### ISSUE TITLE
Bug in GroupCommunicator::BCast for conformal adapted mesh

### ISSUE THREAD

**Issue by hughcars** [mfem/mfem#3631]
Hi, 

I have been working on conformal adaptation in some application code, and have run into an issue with the `GroupCommunicator` which I have not been able to figure out.

Context:
- Performing adaptation on a Fichera cube, with P3 polynomials, solving Poisson equation (Dirichlet 1 on the inner face, and Dirichlet 0 on the outer face, and Neumann between).
- After performing some refinements on each rank, I want to serialize the mesh, in order to repartition. This is basically achieving rebalancing with METIS at the cost of some transfer.
- Adapting with 5 ranks is fine.
- Adapting with 6 ranks causes a BUS error. 

```
==82359==ERROR: AddressSanitizer: BUS on unknown address (pc 0x0001009b7f48 bp 0x00016f5695f0 sp 0x00016f568fc0 T0)
==82359==The signal is caused by a READ memory access.
==82359==Hint: this fault was caused by a dereference of a high value address (see register values below).  Disassemble the provided pc to learn which register was used.
    #0 0x1009b7f48 in mfem::STable3D::Push(int, int, int) stable3d.cpp:73
    #1 0x100c5efb8 in mfem::Mesh::GetElementToFaceTable(int) mesh.cpp:6895
    #2 0x100c6ee64 in mfem::Mesh::FinalizeTopology(bool) mesh.cpp:2980
    #3 0x100fe04a8 in mfem::ParMesh::GetSerialMesh(int) const pmesh.cpp:5483
    #4 0x1008904bc in main ex6p.cpp:173
    #5 0x193a8ff24  (<unknown module>)
    #6 0xad617ffffffffffc  (<unknown module>)
```

The issue being that one of the arguments to `STable3d::Push` is `-1094795586`. I have copied the (relatively small) meshes to a branch `group-communicator-ldof-ltdof-bug`, where after some modifications to `ex6p`, the error can be reproduced with

```
 mpirun -np 6 ex6p --restart
```
which loads the problematic mesh in parallel (which was produced by MFEM using `GeneralRefinement`). Additionally I have placed a few `std::cout` that demonstrate that the issue seems to occur at [this line](https://github.com/mfem/mfem/blob/master/fem/pfespace.cpp#L1605). 

Any help appreciated.

**Comment by v-dobrev** [comment]
Hi @hughcars,

Thanks for reporting this issue, it may have been introduced in the SubMesh PR #2920.

Can you re-try your workflow using the fixes in this branch: https://github.com/mfem/mfem/tree/shared-comms-fix?

I suspect that these fixes will generate `problem.mesh.*` files different from the ones in the branch `group-communicator-ldof-ltdof-bug` and hopefully the new ones will work correctly.

Let me know if the branch `shared-comms-fix` fixes the issues or not.

Thanks!

**Comment by hughcars** [comment]
Hi @v-dobrev,

Thank you for looking into this. Unfortunately that doesn't seem to address the issue, adding assertions into `STable3D::Push`:
```
   MFEM_ASSERT(r >= 0 && r < Size &&
               c >= 0 && c < Size &&
               f >= 0 && f < Size &&
               r != c && c != f && f != r,
               "STable3D::Push : r = " << r << ", c = " << c << ", f = " << f);
 ```
There is still an error:
```
Assertion failed: (r >= 0 && r < Size && c >= 0 && c < Size && f >= 0 && f < Size && r != c && c != f && f != r) is false:
 --> STable3D::Push : r = 147, c = 88, f = -1094795549
 ... in function: int mfem::STable3D::Push(int, int, int)
 ... in file: /Users/hughcars/AWS/palace/build/palace-build/_deps/mfem-src/general/stable3d.cpp:72
```

Let me know if there's any extra information I can provide: unfortunately I've not been able to set up a mwe directly inside of mfem. I could maybe attempt to save off the sequence of refinements, but that would be tricky and require achieving exactly the same partitioning etc. for each stage.

**Comment by v-dobrev** [comment]
Are the generated files `problem.mesh.*` different with the fix in https://github.com/mfem/mfem/tree/shared-comms-fix?

**Comment by hughcars** [comment]
Unfortunately no change when diffing the files.
