### ISSUE TITLE
Evaluation of grid function coefficient leads to memory corruption

### ISSUE THREAD

**Issue by vladimir-yu-fedorov** [mfem/mfem#4623]
Hello,

I have an issue with the evaluation of VectorGridFunctionCoefficient.

I am trying to solve a simple waveguide problem:
$$\vec{\nabla} \times (\vec{\nabla} \times \vec{E} ) - k_0^2 \vec{E} = 0 $$,
where $\vec{E}$ is the electric field, and $k_0$ is the wavevector.  The geometry is a simple elongated box with Dirichlet boundary conditions on the side walls and a specific Robin boundary conditions at the ends which represent the input and output ports:
$$\hat{n} \times (\vec{\nabla} \times \vec{E}) = -i \beta \vec{E} + [\hat{n} \times (-2i\beta E_i \hat{x})]$$,
where $\hat{n}$ is the unit vector normal, $\beta$ is the propagation constant, $E_i(x,y)$ is the incident field and $\hat{x}$ is the unit vector along the $x$ coordinate.

As you can see, the Robin boundary condition in this problem depends on the incident field  $E_i$. To implement such boundary condition I use a subclass of VectorCoefficient where I hard coded the incident field $E_i$. However, in future I would like to define $E_i$ outside and pass it into the Robin bc class using VectorGridFunctionCoefficient. However, on the way to implementing this approach, I encountered a very strange problem. When I try to evaluate the corresponding VectorGridFunctionCoefficient inside the Robin bc class (without even using the results of this evaluation) I see that the otherwise correct solution becomes distorted. Thus, a simple evaluation of an arbitrary VectorGridFunctionCoefficient leads to some memory corruption. Can you please help me to understand what is going on.

In the attachment I put the MWE (the code, the mesh, and a makefile template to build, run and visualize the solution) which demonstrates the problem. To fix the distorted solution issue, you just need to comment out line 62 in the ```gfcoef_issue_mwe.cpp```. The following figures show the correct solution and the distorted one:

Distorted solution:
<img src="https://github.com/user-attachments/assets/31bddc92-4fae-4351-8246-3bfa1eac58dc" width="50%" />

Correct solution:
<img src="https://github.com/user-attachments/assets/b507f377-0bcc-4d7a-ad8c-92aec7765580" width="50%" />

MWE files:
[gfcoef_issue_mwe.zip](https://github.com/user-attachments/files/18072266/gfcoef_issue_mwe.zip)

**Comment by pazner** [comment]
I think this is because the internally cached `DofTransformation` in the finite element space becomes invalidated.

https://github.com/mfem/mfem/blob/c3771b335259cfd740d0037b1ec8d530ad09b6cc/fem/fespace.hpp#L282

**Comment by vladimir-yu-fedorov** [comment]
I am sorry, I do not have enough knowledge to understand your tip. Is it possible to fix it?

Meanwhile, I tried to run the above example using the AddressSanitizer (```-fsanitize=address``` flag) and it showed me the heap out of bounds error:
```
==61327==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x506000100a60 at pc 0x756a7d6fb42e bp 0x7ffe2de65990 sp 0x7ffe2de65138
READ of size 16 at 0x506000100a60 thread T0
    #0 0x756a7d6fb42d in memcpy ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors_memintrinsics.inc:115
    #1 0x756a7af3fce3 in mfem::Vector::operator=(double const*) (~/mfem/lib/libmfem.so.4.7.1+0x33fce3) (BuildId: d4f7ef6abfc7121490047f1fef67fa3dc1ca435a)
    #2 0x756a7b6bd984 in mfem::ND_DofTransformation::TransformDual(mfem::Array<int> const&, double*) const (~/mfem/lib/libmfem.so.4.7.1+0xabd984) (BuildId: d4f7ef6abfc7121490047f1fef67fa3dc1ca435a)
    #3 0x756a7b6bc9c6 in mfem::DofTransformation::TransformDual(double*) const (~/mfem/lib/libmfem.so.4.7.1+0xabc9c6) (BuildId: d4f7ef6abfc7121490047f1fef67fa3dc1ca435a)
    #4 0x756a7b7ff473 in mfem::LinearForm::Assemble() (~/mfem/lib/libmfem.so.4.7.1+0xbff473) (BuildId: d4f7ef6abfc7121490047f1fef67fa3dc1ca435a)
    #5 0x756a7c04297c in mfem::ParLinearForm::Assemble() (~/mfem/lib/libmfem.so.4.7.1+0x144297c) (BuildId: d4f7ef6abfc7121490047f1fef67fa3dc1ca435a)
    #6 0x756a7b61bf8c in mfem::ParComplexLinearForm::Assemble() (~/mfem/lib/libmfem.so.4.7.1+0xa1bf8c) (BuildId: d4f7ef6abfc7121490047f1fef67fa3dc1ca435a)
    #7 0x61e832c05cb8 in main (~/gfcoef_issue_mwe+0x18cb8) (BuildId: 376cd2dcb12f2ed435a0ae0d0dc81b9b890d59a9)
    #8 0x756a7a42a1c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #9 0x756a7a42a28a in __libc_start_main_impl ../csu/libc-start.c:360
    #10 0x61e832c04284 in _start (~/gfcoef_issue_mwe+0x17284) (BuildId: 376cd2dcb12f2ed435a0ae0d0dc81b9b890d59a9)

0x506000100a60 is located 32 bytes after 64-byte region [0x506000100a00,0x506000100a40)
allocated by thread T0 here:
    #0 0x756a7d6fe6c8 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:98
    #1 0x756a7b80f3a4 in mfem::VectorFEBoundaryTangentLFIntegrator::AssembleRHSElementVect(mfem::FiniteElement const&, mfem::ElementTransformation&, mfem::Vector&) (~/mfem/lib/libmfem.so.4.7.1+0xc0f3a4) (BuildId: d4f7ef6abfc7121490047f1fef67fa3dc1ca435a)

SUMMARY: AddressSanitizer: heap-buffer-overflow ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors_memintrinsics.inc:115 in memcpy
Shadow bytes around the buggy address:
  0x506000100780: fd fd fd fd fa fa fa fa fd fd fd fd fd fd fd fd
  0x506000100800: fa fa fa fa fd fd fd fd fd fd fd fd fa fa fa fa
  0x506000100880: fd fd fd fd fd fd fd fd fa fa fa fa fd fd fd fd
  0x506000100900: fd fd fd fd fa fa fa fa fd fd fd fd fd fd fd fd
  0x506000100980: fa fa fa fa fd fd fd fd fd fd fd fd fa fa fa fa
=>0x506000100a00: 00 00 00 00 00 00 00 00 fa fa fa fa[fa]fa fa fa
  0x506000100a80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x506000100b00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x506000100b80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x506000100c00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x506000100c80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==61327==ABORTING
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[12579,1],0]
  Exit code:    1
--------------------------------------------------------------------------
make: *** [makefile:10: run] Error 1
```

**Comment by pazner** [comment]
Hi @vladimir-yu-fedorov,

I think this is an internal issue in MFEM (and my overly brief comment earlier was pointing out where the problem is). To expand a bit:

When the `VectorGridFunctionCoefficient` is evaluated in the linear form, it ends up calling `GridFunction::GetVectorValue`, which, for `ElementType` `BDR_FACE`, calls `doftrans = fes->GetElementVDofs(i, vdofs)`, which clobbers the internal `DofTransformation`, which is then needed in `LinearForm::Assemble` by `doftrans->TransformDual(elemvect)`.

I don't know the best way to resolve this issue, but maybe @v-dobrev @mlstowell @psocratis have ideas.

**Comment by psocratis** [comment]
Hi @vladimir-yu-fedorov, as @pazner said this is a bit of a complicated issue and we will discuss it with the rest of the team to decide on a fix. In the meantime you can fix it by adding this line 
````cpp 
doftrans = fes -> GetBdrElementVDofs (i, vdofs);
````  
just before 

https://github.com/mfem/mfem/blob/9a9087e20b214cfb74f684429bd912e21b9381b3/fem/linearform.cpp#L263-L266

This will recompute and overwrite the `doftrans` again after it was overwritten inside the integrator. This is not a nice fix, more like a hack, until with figure something else out. 

I hope this helps.

Best,

Socratis

**Comment by vladimir-yu-fedorov** [comment]
Dear Socratis,

Your hack works. Will wait for a more permanent solution. Thank you.

**Comment by v-dobrev** [comment]
One option to resolve this issue may be to introduce new versions of the methods `Get{Element,BdrElement}VDofs` with a singnature like this:
```c++
   virtual void GetElementVDofs(int i, Array<int> &vdofs, DofTransformation &doftrans);
```
Also, we can add a method in `DofTransformation`, e.g. `bool Empty() const`, that tells it the `DofTransformation` is empty, i.e. identity. Or maybe we can just modify `DofTransformation::IsIdentity()` to return `(dof_trans_ && dof_trans_->IsIdentity())`.

With such additions, assembly will look like this:
```c++
   // ...
   Array<int> vdofs;
   DofTransformation doftrans;
   // ...
   for (int i = 0; i < mesh.GetNE(); i++)
   {
      // ...
      fes->GetElementVDofs(i, vdofs, doftrans);
      // ...
      if (!doftrans.IsIdentity())
      {
         // ...
      }
      // ...
   }
```
@pazner, @mlstowell, @psocratis, what do you think about this approach?

**Comment by pazner** [comment]
Yes, I think that approach should work.

Even better (but a breaking change) would be to just return the `DofTransformation` by value in all cases — the pattern of returning a reference/pointer to an internal object that can be invalidated mysteriously in the future seems to cause us a number of problems. Do we have performance regression tests to measure if the performance impact of such a change would be meaningful? (Maybe timing the sample runs, but maybe we have something more systematic).

**Comment by v-dobrev** [comment]
Returning `DofTransformation` by value from `GetElementVDofs(int i, Array<int> &vdofs)` has unnecessary overhead when used as
```c++
   doftrans = fes->GetElementVDofs(i, vdofs);
```
This involves constructing a temporary `DofTransformation` on the stack and then copy-assigning that to `doftrans`. If used (inside the loop) as
```c++
   DofTransformation doftrans = fes->GetElementVDofs(i, vdofs);
```
the copy will be avoided but construction, initialization (e.g. heap allocation for the `Array<int>` data member), and destruction costs will be incurred on each iteration.

 On the other hand, the call (with `doftrans` constructed outside the loop)
```c++
   fes->GetElementVDofs(i, vdofs, doftrans);
```
avoids the new object construction, the heap re-allocation, and the copy-assignment without any drawbacks -- at least I don't see any drawbacks.

**Comment by pazner** [comment]
> Returning `DofTransformation` by value from `GetElementVDofs(int i, Array<int> &vdofs)` has unnecessary overhead when used as
> 
>       doftrans = fes->GetElementVDofs(i, vdofs);
> This involves constructing a temporary `DofTransformation` on the stack and then copy-assigning that to `doftrans`.

This should be a move-assignment rather than a copy-assignment.

> If used (inside the loop) as
> 
>       DofTransformation doftrans = fes->GetElementVDofs(i, vdofs);
> the copy will be avoided but construction, initialization (e.g. heap allocation for the `Array<int>` data member), and destruction costs will be incurred on each iteration.

Yes, this cost would be incurred if returning by value and doesn't seem avoidable. It would be interesting to see if this is non-negligible (that's why I asked about performance regression tests).

> On the other hand, the call (with `doftrans` constructed outside the loop)
> 
>       fes->GetElementVDofs(i, vdofs, doftrans);
> avoids the new object construction, the heap re-allocation, and the copy-assignment without any drawbacks -- at least I don't see any drawbacks.

The drawback is that, unless the two-argument version is changed to no longer return a pointer to the internal object, it's still easy to encounter bugs like the one reported in this issue.

**Comment by v-dobrev** [comment]
> > Returning `DofTransformation` by value from `GetElementVDofs(int i, Array<int> &vdofs)` has unnecessary overhead when used as
> > ```
> >   doftrans = fes->GetElementVDofs(i, vdofs);
> > ```
> >   
> > This involves constructing a temporary `DofTransformation` on the stack and then copy-assigning that to `doftrans`.
> 
> This should be a move-assignment rather than a copy-assignment.
> 
> > If used (inside the loop) as
> > ```
> >   DofTransformation doftrans = fes->GetElementVDofs(i, vdofs);
> > ```
> >   
> > the copy will be avoided but construction, initialization (e.g. heap allocation for the `Array<int>` data member), and destruction costs will be incurred on each iteration.
> 
> Yes, this cost would be incurred if returning by value and doesn't seem avoidable. It would be interesting to see if this is non-negligible (that's why I asked about performance regression tests).
> 
> > On the other hand, the call (with `doftrans` constructed outside the loop)
> > ```
> >   fes->GetElementVDofs(i, vdofs, doftrans);
> > ```
> >   
> > avoids the new object construction, the heap re-allocation, and the copy-assignment without any drawbacks -- at least I don't see any drawbacks.
> 
> The drawback is that, unless the two-argument version is changed to no longer return a pointer to the internal object, it's still easy to encounter bugs like the one reported in this issue.

This is not a drawback of the the method I'm suggesting but of the existing 2-argument version.

As a solution to the issue with the current two-argument version, we can simply make it trigger an error if used in a case that requires the use of `DofTransformation` with an explanation to switch to using the new 3-argument version that I'm proposing. This will change current behavior, so to preserve backward-compatibility for some time, before introducing the error message, we can just issue a warning instead.

**Comment by hughcars** [comment]
> > > Returning `DofTransformation` by value from `GetElementVDofs(int i, Array<int> &vdofs)` has unnecessary overhead when used as
> > > ```
> > >   doftrans = fes->GetElementVDofs(i, vdofs);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This involves constructing a temporary `DofTransformation` on the stack and then copy-assigning that to `doftrans`.
> > 
> > 
> > This should be a move-assignment rather than a copy-assignment.
> > > If used (inside the loop) as
> > > ```
> > >   DofTransformation doftrans = fes->GetElementVDofs(i, vdofs);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > the copy will be avoided but construction, initialization (e.g. heap allocation for the `Array<int>` data member), and destruction costs will be incurred on each iteration.
> > 
> > 
> > Yes, this cost would be incurred if returning by value and doesn't seem avoidable. It would be interesting to see if this is non-negligible (that's why I asked about performance regression tests).
> > > On the other hand, the call (with `doftrans` constructed outside the loop)
> > > ```
> > >   fes->GetElementVDofs(i, vdofs, doftrans);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > avoids the new object construction, the heap re-allocation, and the copy-assignment without any drawbacks -- at least I don't see any drawbacks.
> > 
> > 
> > The drawback is that, unless the two-argument version is changed to no longer return a pointer to the internal object, it's still easy to encounter bugs like the one reported in this issue.
> 
> This is not a drawback of the the method I'm suggesting but of the existing 2-argument version.
> 
> As a solution to the issue with the current two-argument version, we can simply make it trigger an error if used in a case that requires the use of `DofTransformation` with an explanation to switch to using the new 3-argument version that I'm proposing. This will change current behavior, so to preserve backward-compatibility for some time, before introducing the error message, we can just issue a warning instead.

I would argue that the 2 argument changed to return by value is worth having, as a convenience version, but if someone is repeatedly using this within a loop, hoisting to the 3 argument version is absolutely worth it. The 2 arg would then only be a wrapper around the 3 arg going forward, with a warning in the 2-arg saying there's a better 3-arg version. Anyone deciding between the two would recognize that hoisting that allocation out of a repeated call would probably be worth it, as that's a pretty common c++ optimization done when working with heap allocations.

**Comment by pazner** [comment]
@vladimir-yu-fedorov, can you see if your issue is resolved now that #4877 is merged? Sorry this took so long to address.
